apiVersion: apps/v1
kind: Deployment
metadata:
  name: orange-utilities
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orange-utilities
  template:
    metadata:
      labels:
        app: orange-utilities
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: api
          image: okteto/orange-utilities:java-gradle
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: orange-utilities
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    app: orange-utilities
spec:
  type: ClusterIP
  ports:
    - name: orange-utilities
      port: 8080
  selector:
    app: orange-utilities